language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export ANDROID_HOME=~/builds/hackersInCTS/spinach-android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter 1,3,10 --no-ui --force
script:
  - ant release
after_script:
  - git clone https://github.com/FloydPink-Public/spinach-android.git
  - cd spinach-android
  - git checkout --orphan gh-pages
  - git rm -rf .
  - cp ../bin/Spinach-release.apk .
  - git add .
  - git commit -a -m "Committed by Travis-CI"
  - git push --repo https://floydpink-public:Public-FloydPink@github.com/FloydPink-Public/spinach-android.git gh-pages
